//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiSpcMq.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DsiSpcMq.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   JQI62fq8EqUFFgwIfAqC97MIyoM6bkvyqGL7ASgn60N72dYuYR8WJQxd7Yr9TxiLMSnTB7ObTCQFDVOoP1PTY8hbiZQCr9zsXI52ZMN5jpG4JeMK+WE2s0+nFJJE1CT9WoMSi/ikESF7Ma8R5Uh/eFQEQ/uUwy+OA0ZpWsKN4pw=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yj4moYLtvqBIMWabgwIzU9kKn4yJH0hfzutHXbUG8YWlwKsjgwYsb7+A7gYKwXeAtb/c/v21bt2Y1k7OIZOaFtusE4yZ0zw/FWObTH0jP9wD9wBj9SXonwtXOJWsHTXije9RL5b8Zml0Wpi1CLoou7SWmGF14nUl9K41UgyRjbI=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeyName {
            get {
                return ResourceManager.GetString("KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B76pWa4k+tHio4+EzwtF0YFxp3cJLQuIDCBBIA7HjVd7+JpFvUcpqjCsCCJ/VWk6LS+eoFf3anC6FZhqxnZ6BrxZEYYcC2Dmb6sYqWI5hOpeMetlU/r3nDIqlS0qLILSeoBvI7isgWeikr+5XBZTrPlqPUH0J7pGlJMmGEzB4/s=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NameSpace {
            get {
                return ResourceManager.GetString("NameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   do1xtOBNbuBxO+h4EfwydqwsQnzoYLMUf5j3D3qyJktYseS+qr9cjKp6+r7A7CSNKs0YfRTfiU4XBlVR27oSww16oQW8rqE2U0WdrdvW3di7tVu5kWdYLgfi5NeiMuh6dKb98lzA6ZAqnIjRe5QrZLPhH3QzCdRp3cOmhJYetmc=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VeC0xyia+rqw73tsvByyjAUF3X7ka/s0EgbVnZPJiJgB8841hJX1ROLmzzJNGLKKPRusp9CLlzEWrpDq3msRpPxYfu6IMlE7P833iOel1jNhEH98gliOWzdG3rOYo3N7th7lgFOzOyRCHcgxvZlIEZnyRfjODcdmUvmEz8f3cxc=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesBasicInfo {
            get {
                return ResourceManager.GetString("QueuesBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fkE8esEIB7KzXr0kFY5vUYJlrxqKpMEhNAoUntK8RuHdtmGuKCTc3HwAsC6xH1/kCBlScnf+gGA0ICYCeOMOO2JO/LPFQ0YpApMfK13obiXWRXjKDON1LqIIpDpTW33zKlXuWGH3e5OdoGUPzNLuqTbAY4j/DS5sWrM3y2ABVFM=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesLegacy {
            get {
                return ResourceManager.GetString("QueuesLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2ZLd7bZDHbTDrPsAddZBc9WVijG7cqaqCPaEd6U0DJc+1UNcAlTCowTcqjB1hbtaAMJHv0Wlw548PtrNht9gJK+DZ/GM63qH727IGmvDvENnl+lD1H8ATBJWXVDlQDRJXLRjPk1dnnptU3K8ROH+EpgeclezhB8n/5TVdoZchnI=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesMeasureOne {
            get {
                return ResourceManager.GetString("QueuesMeasureOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xcqY7v6HwQG6p+h7IiyM94rGmxfozydrfj/CRJVPcK0Yh90ojU+qQplLFCJdrtKalFis/g5SnxjpIUW6T7pcUqE61S+iCt+a5A7XSUbbg+sI+IEgansygLDArsxScfNmLDKb9qyOBwViN7gNUzvS2+MqFkTDETarED4c/0anar4=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesMeasureThree {
            get {
                return ResourceManager.GetString("QueuesMeasureThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   v8LAwqmgzpZXvbA+RKFtvfMo7srGAJkCeRarsGUR7VNv8f5RV3nvv6Bl0M54vXR+UP0LzQOrhzd4NqpqFpK75LQhWjjjFnbG2mWLgAK7dvSW6YIB7ifjfu0yfhiuA7rZQtbXmvq3x90H61p4m0B1N0++VTobRL/AjnaBXR+YKqU=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesMeasureTwo {
            get {
                return ResourceManager.GetString("QueuesMeasureTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q3ULyWZVZw8vm72r+gXiZWEKQHTp/+eSjbsrr77G5P9XzQOCmbeKppCtbaMSY3c9p4YHvsu+08WODPO05PytJs1agDb28rYWksXlMklOSSHhNNqeKER+vQ3jHqHF+FP2ldcAQY1FmmLJXJQEKUd80Iz1W0paa8vbUioj63OX/Q8=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesStatOne {
            get {
                return ResourceManager.GetString("QueuesStatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   58A4J6Gvv/FiIt5+EVIjeX/XPXZH92FYNl4+I/PMMMTcwfXHZttu63NpI8r6bB7gFOxYC+JaFQTbQNk9lIm8h6eL8hW8XyDEycv3Ierma2BmkM2SIDpsXO2J6Fh11h9jYjpiaETxSB0qgxENon42xIzvqwWHVZZ1GMBJLUk1OkE=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesStatThree {
            get {
                return ResourceManager.GetString("QueuesStatThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MQNW6sEzNMbCIjy9lCKtibsZuKDvhscCHdNBX7eCdVXtGDmBKLW+iHJ03wVYaIeQfH7yh4NO8xhRHAbTI4rag1tYtYwPsSqJ2E17h+JmpNsUl6ISMuFLkiw6t4e4U5nUSQE18oAgg6ul8quZMVxs/xZ4coSZ1icshux+6gD/mio=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QueuesStatTwo {
            get {
                return ResourceManager.GetString("QueuesStatTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ro76IO4c93fxcE44fs6gnKiJqkqqnWtnlS+SgCoNybrFiFP1/HbDrXtdJYH5wmiTC4tEMtf8IOKL3P828/4q8xJb+IJ8XWTEq0KuXwgbBhWgtXXEvfvY+Ns5lQSTcW4AmYUn4XTxrswqDXWBHm64C9BlD3bqzLPF2AmQ6Sln5JA=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyBasicInfo {
            get {
                return ResourceManager.GetString("RoutingKeyBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XkaoV4YTqMpjrESUMSwmKGSFwIURIVuTfvUO+jpTEx5qrBZ3XoxeddF+ZazWHDOgxEsnff0DSXmEHI9fLGD1BKaslqs203bPXa3/AAFXA0Su790Jmyx+FZeapxCwzXof6CQCqmVhfJFzeECi/b5gUgWeaCgaF4aWOqKYSjHn4/o=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyLegacy {
            get {
                return ResourceManager.GetString("RoutingKeyLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   znV3nHzYkAORyCn6IMDF1c8OsDMcMoTcrydHD9gqgYoAoHXAILaXlGW6UBQDFK0vD/wYy7+jFSD0a3PkVMcKHCym1ENzEGcwESjWuyI7kWjwSpJ6Mi4RrxqlSg6CUp+XMI6mcDHmJfvO6MX74NHPNat98lSr/DqIEVktnqepbgw=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyMeasureOne {
            get {
                return ResourceManager.GetString("RoutingKeyMeasureOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bxwGR1iD+YbX9v6nTIsvtke2nET46W3NR1+M7eXZGSJCCuPKW8BI7itr+M+JIylhVzy22/UWlS3c22445QyR517fsd1Q9d5WhNZLNbKqYGtxBeIaZsLNv5yNc+syWSPuoS2dP7zZQ2fpVz0bND31MPAGE89X/5uwN8W3JQMOrfg=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyMeasureThree {
            get {
                return ResourceManager.GetString("RoutingKeyMeasureThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FgUNcVmi0PACLYXcpmHOCXklcMLK/Fw+PXUf0TXdod7zXDVH8qJ0Ct42IwSOk9vc9JaY+9pyxGOHrKZK7zxnLyGj35+OCO4XBJU6e/CBuN0XeGRQySVIkwC3c1rp1z1OMwftnVMAcXxjMQkULhHw3ZmB+SO/wPZq9gdL5EdgGdA=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyMeasureTwo {
            get {
                return ResourceManager.GetString("RoutingKeyMeasureTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   251NVoVp3AUT4iEASF7bkWBvobB0fDqm34qO8nAmR0o2fkerabyDS6J2zyeozGs1YeGCNuv/0Ksnq/Kcaf1nkBGdP9EtbnBqpYQH9uM+yj7jV0bWeqTcbZjOUAbFgNo9tVe7GI5g4dIu7aBRUrUzZ74lbpMap9WMaySFbZ/CqoU=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyStatOne {
            get {
                return ResourceManager.GetString("RoutingKeyStatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xWhEXnG1mVCmdN1MW6m6/Bgsktjwmb6ti90YC6rhgUY9yCmcYL2RfNq6RgQYYNPTs2qHUF4jx8ikO7PkkfyUePel3sziJWkJbBFRVK2vDxbzvqi7CHxuBCWzMCnV3jTv9kjFGON+h/rZaXRvaaA5WemgmmuB7dL8Lg5kqwsWZjI=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyStatThree {
            get {
                return ResourceManager.GetString("RoutingKeyStatThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I+H4TLnRplMfyjtcLBIAMzWFTUkFLMQvDByOPKXPvv5Wh5J7OC+G3csbvp10K7Zg5g2wGsAwHjcBBQUEfO9227q8Z6iF1Pq5oHAdPvKcq2xl+6mXgw5OfZuRaI84dvUC3zrzglzgLRVWMdZ3TZrFIpwjLNuO290IMQ/tysiVqhw=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingKeyStatTwo {
            get {
                return ResourceManager.GetString("RoutingKeyStatTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3TBUArdb2H/pYhNTfwwA0W2z492RqMbebhsOBRRfVdHxk69rAdNpoWGSrrOWFxsUjrtKm7n4X3rQP0mMYnnWMOHOZBCPw8QG23ugT6oFRiZDBsDnvArzlUMERyRiVMnYyv2WZ/qrWFTAP71qrYjdLTI8ZZ/Yfb3m59dTwelWaV8=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingPatternBasicInfo {
            get {
                return ResourceManager.GetString("RoutingPatternBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fcyB6BIh5bZFY4LWRfx+oS5izH+jT/jVqB1Ed7QOudPxbNG5eIVth6VBnLh8PULyRIfLor6zW/2wrW6no3rTtfqW0ek4YHw1HqGoE4GRcbd91T0z/+Etg5uN4pgFm+yy8AfwBZAFg0PWo5VcR+C8tPApEjNqMe0isww5meLd6s0=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingPatternLegacy {
            get {
                return ResourceManager.GetString("RoutingPatternLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hyIYODhSDp3Wjw0lrnRZ7eHIT4sP8vrvO/fvfRoVmZ0OI8weDNjUXXEqZ+CKhlzqqqFuzcYhRKoSHu1GRWZiKYzYx6dNh7RAAeT8mZppUAsguKpJeQKgMr3Btiy1lfF2Wt1asSyaRSIrWehzidrnhdU9GZXfO+M+Eo3YijWTcv4=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingPatternMeasure {
            get {
                return ResourceManager.GetString("RoutingPatternMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MEBo9FrMbJLohb2tZQtnRqHmz9t8iQZSuTNtn9o05OSTsbryPpesxWUaTPBJXfQGaXHiAllfSxHytqACrkWEYYf3XZP6kkns1kZtjPXtWy8546TYPCEXyGnK1tXYy6bBpocgFxWgrPH+2t7oVss4joCheWM7PH60QY2ufa4u2MA=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RoutingPatternStat {
            get {
                return ResourceManager.GetString("RoutingPatternStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3tAmPwiPl26M4a7rAVmjqM2XKyP1Se98uFhwhXVoUGjzJlJwDUeYYBqRA/lukSc5kxFaIhoaGY7CAiZRGlbmxWyBtBmR0PXi1ovJnx3mcli6Qw2/riyAnw0B6rjHFmu0o0AIi6E0UgnRW9HspcjDTIxbFjGSL22xZafzFdyd4Po=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerHostName {
            get {
                return ResourceManager.GetString("ServerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hh6nyOjjKlPKAUxFiMpM8wri2LomAjVQDx8IdNIqwIbpgv/iIXCsPYMMeotB7FiRYYBnbt7JIDGD9gfZx6neITDlIcjG+/+0kuogCvz9P5qFD9s9xq/xTgbo4e9unO4lUm6b8ykm2AJ+Io0QEPc+UGCVcc3T9w/jcqBVGNE/Jk8=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZNCvS8RaEbcxEMjEJKDhrBYnxUwRn1fyo15/kMtRuBU688HYMJY/iT8I9QuCXG4I7kINXEtMCQy1W0uHvr6/FGkhjWH6+SRrM6ajMCLWXXkb78u8+a9ulCGT2g25kZ19IEfhnEPcfM8ckhJI/ooqnJW1/EcfMBCWFDca6zaw6/I=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5Q1pqGxuVMGh6TzHwNJoA8wY6wyu42F1B1O3l1FA9G6ZrSLoRIsYmjaR8VJ4wubOu0Au22OOIxqmm0ok0SYP/yt7AVPFRZT/zTTdWNVIPYX4pbUYEkGMVxuu2WEFOnTGZkv6BOKKiZnDE/wctMvbLFAJvIEsGIiUidKM0N15Dnc=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string topicName {
            get {
                return ResourceManager.GetString("topicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SkYmLrKl0uaZO9VEDfq53gpm2fKywc7ggmZ82Im1h5xiJK5v9Ez6LfVI2Kb8/tc/hRZ3bDKfCR68vhTnGMVtIRnOKaa4VIlschLZ4LMuyT/0oMEVpVwpTa91Jb3H3eDTKkNf3nCO3MoP/oKyYwIjy2PqRJBG1yOx0fGeh9hty98=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
